name: 'tool'

on:
  push:
    tags:
      - '*'
      - '!tip'
    branches:
      - '*'
    paths:
      - '.github/workflows/tool.yml'
      - 'tool/**'
jobs:

  tool:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: '1.13.x'
    - name: golangci-lint
      run: |
        cd tool
        curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b ./ latest
        ./golangci-lint run -v
#    - name: script test
#      run: |
#        go get -u github.com/kyoh86/richgo
#        richgo test -v ./...
    - name: goreleaser
      run: |
        cd tool
        curl -fsSL https://git.io/goreleaser | sh -s -- --snapshot --skip-publish --rm-dist
        cp dist/issue-runner_linux_amd64/issue-runner ../issue-runner
    - name: binary test
      run: |
        ./tool/test.sh
    - name: prepare artifacts
      run: |
        mkdir -p tool/dist/binaries
        cd tool/dist/binaries
        mv ../issue-runner_linux_amd64/issue-runner issue-runner_lin_amd64
        mv ../issue-runner_windows_amd64/issue-runner.exe issue-runner_win_amd64.exe
    - uses: 1138-4EB/tip@gha-tip
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        cwd:   ${{ github.workspace }}
        files: |
          tool/dist/binaries/*
